BASH_TEMPLATE = """#!/bin/bash
# -----------------------------------------------------------------
# Auto-generated Retry Script
# Configuration generated by the Tkinter Bash Workflow Generator.
# -----------------------------------------------------------------

# User-defined variables
MAX_TRIES={MAX_TRIES}
WAIT_SECONDS={WAIT_SECONDS}
COMMAND_TO_RUN="{COMMAND_TO_RUN}"
LOG_FILE="/tmp/retry_log_{TIMESTAMP}.txt"

# --- Main Retry Logic ---

echo "Starting workflow at $(date) (PID: $$)" > $LOG_FILE
echo "Command: $COMMAND_TO_RUN" >> $LOG_FILE
echo "Max Retries: $MAX_TRIES, Delay: $WAIT_SECONDS seconds" >> $LOG_FILE
echo "--------------------------------------------------------" >> $LOG_FILE

for ((i=1; i<=MAX_TRIES; i++)); do
    echo "Attempt $i/$MAX_TRIES..." | tee -a $LOG_FILE
    
    # Execute the command
    # Output is piped to the log file
    if $COMMAND_TO_RUN >> $LOG_FILE 2>&1; then
        echo "Command succeeded on attempt $i." | tee -a $LOG_FILE
        echo "Workflow finished successfully at $(date)." | tee -a $LOG_FILE
        exit 0 # Exit the script successfully
    else
        EXIT_CODE=$?
        echo "Command failed (Exit Code: $EXIT_CODE) on attempt $i." | tee -a $LOG_FILE
        
        if [ $i -lt $MAX_TRIES ]; then
            echo "Waiting $WAIT_SECONDS seconds before retrying..." | tee -a $LOG_FILE
            sleep $WAIT_SECONDS
        fi
    fi
done

# If the loop completes without success
echo "--------------------------------------------------------" | tee -a $LOG_FILE
echo "CRITICAL FAILURE: Command failed after $MAX_TRIES attempts at $(date)." | tee -a $LOG_FILE
exit 1 # Exit with a non-zero status
"""